### PR TITLE
Update languages script

### PR DESCRIPTION
**Pull request by alexander-nitsche**
Hi Martijn,

this PR is about providing a script for automatic language files updates, including a first bunch of updated files. It is related to issue #44 . What remains is:

- [x]  Is the location of the script fine or should it be moved to another location?
- [x] Would add the final class path to the automatic class loading paths of the dev context of the composer.json. 
- [ ] <s>Should it be blown to a full Symfony Console Command with parameters and being executable via vendor/bin? The Symfony Console package is already a dependency of this package in development context.</s> => Composer says "If a package contains other scripts that are not needed by the package users (like build or compile scripts) that code should not be listed as a vendor binary.".

Greetings, Alex

### CODE REVIEW

**Comment by alexander-nitsche** [comment]
The console output looks like:
```
Updating 75 language files on 2023-03-17 19:18:45 CET.
File hyph-af.tex has been UPDATED.
..
File hyph-de-ch-1901.tex has been UPDATED.
Error: Call to URL http://mirror.ctan.org/language/hyph-utf8/tex/generic/hyph-utf8/patterns/tex/hyph-de.tex failed with
{
    "status": 404,
    "response": "<html>\r\n<head><title>404 Not Found<\/title><\/head>\r\n<body bgcolor=\"white\">\r\n<center><h1>404 Not Found<\/h1><\/center>\r\n<hr><center>nginx\/1.14.2<\/center>\r\n<\/body>\r\n<\/html>\r\n ..",
    "cURL error": "",
    "cURL error number": 0
}
File hyph-el-monoton.tex has been UPDATED.
..
File hyph-zh-latn-pinyin.tex has been UPDATED.
Result: 75/75 files processed, 74 changed, 0 unchanged and 1 failed.
```

**Comment by alexander-nitsche** [comment]
I split off the updated language files to PR #46  to ease review.

**Comment by alexander-nitsche** [comment]
Done :)

**Comment by alexander-nitsche** [comment]
Hi Martijn, 

how to proceed here: the checks require changes, where the Codacy can be met with a new commit, but the Travis CI cannot pass as the service is off-duty. I could make Codacy happy with a new commit and you might want to unset Travis CI as required?

Greetings, Alex

**Comment by alexander-nitsche** [comment]
Hi Martijn,

I have replaced testing by Travis CI with a GitHub action. This makes PRs #49 and #50 obsolete.

Also, I've moved to not committing the updated language files directly to the master branch, but creating a feature branch and first creating a PR from that branch to the master branch before automatically merging the PR - if the required checks pass.

To merge this PR, we need to disable Codacy and Travis CI as required checks. Codacy and StyleCI conflict with each other, and Travis CI is no longer available. If you agree, we can finalize this PR together in a short call.

Greetings, Alex

**Comment by alexander-nitsche** [comment]
Temporarily disabling GitHub checks is explained [here](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/managing-a-branch-protection-rule#creating-a-branch-protection-rule).

**Comment by alexander-nitsche** [comment]
Hi Martijn,

with the latest changes the updated language files are automatically published - if the previous head of the master branch was also published. This helps to automatically provide package users with the latest language updates while ensuring that no non-language files  commits are accidentally published.

It is tested thoroughly.

Greetings, Alex

**Comment by alexander-nitsche** [comment]
Added some tests for the build/ classes to increase confidence.

**Comment by alexander-nitsche** [comment]
Rebased.

**Comment by alexander-nitsche** [comment]
The outcome of this PR will look like this:

Tests GitHub Action
syllable-tests-github-action

Update Languages GitHub Action
syllable-languages-github-action

Automatic commits and release
syllable-languages-commits

**Comment by vanderlee** [comment]
@alexander-nitsche , since you're making regular improvements, do you think this is ready to merge? I finally managed to find how to remove the Travis-CI check, and you should have permissions to merge it, so please do when you feel it's ready.

**Pull request merged**
