### PR TITLE
Fix PHP 7.4 Deprecation Warning

### PR DESCRIPTION
**Pull request by dargmuesli**

### CODE REVIEW

**Comment by dargmuesli** [comment]
@vanderlee any ETA on merging this?

**Comment by dargmuesli** [comment]
🔥

**Comment by dargmuesli** [comment]
Will this be part of a release soon? 🙈

**Comment by vanderlee** [comment]
Sorry for the delay; computer hardware issues. It's tagged 1.5.3 and should appear in Packagist automatically.

**Comment by dargmuesli** [comment]
Oh no, I hope everything is good now. Thanks for your work! :)

**Pull request merged**
